In [8]:
import numpy as np
import seaborn as sns 
import pandas as pd
from tqdm import tqdm
import cv2
from tensorflow.keras.applications import Xception
from tensorflow.keras.utils import plot_model

In [9]:
TRAIN_PATH = '../Steel Defect Detection Dataset'
TRAIN_IMAGES = '../Steel Defect Detection Dataset/train_images'
TEST_IMAGES = '../Steel Defect Detection Dataset/train_images'

In [10]:
df_train = pd.read_csv(TRAIN_PATH + '/train.csv')
df_submission = pd.read_csv(TRAIN_PATH + '/sample_submission.csv')

In [11]:
df_train.head()

ImageId  ClassId                                      EncodedPixels
0  0002cc93b.jpg        1  29102 12 29346 24 29602 24 29858 24 30114 24 3...
1  0007a71bf.jpg        3  18661 28 18863 82 19091 110 19347 110 19603 11...
2  000a4bcdd.jpg        1  37607 3 37858 8 38108 14 38359 20 38610 25 388...
3  000f6bf48.jpg        4  131973 1 132228 4 132483 6 132738 8 132993 11 ...
4  0014fce06.jpg        3  229501 11 229741 33 229981 55 230221 77 230468...

In [12]:
df_train.shape

(7095, 3)

In [13]:
df_train = df_train.iloc[0: 1000]

In [14]:
import matplotlib.pyplot as plt

In [15]:
img = plt.imread(TRAIN_IMAGES + '/0002cc93b.jpg')

In [16]:
img

array([[[ 70,  70,  70],
        [ 70,  70,  70],
        [ 68,  68,  68],
        ...,
        [ 48,  48,  48],
        [ 48,  48,  48],
        [ 50,  50,  50]],

       [[ 66,  66,  66],
        [ 68,  68,  68],
        [ 68,  68,  68],
        ...,
        [ 48,  48,  48],
        [ 49,  49,  49],
        [ 51,  51,  51]],

       [[ 61,  61,  61],
        [ 64,  64,  64],
        [ 65,  65,  65],
        ...,
        [ 49,  49,  49],
        [ 51,  51,  51],
        [ 54,  54,  54]],

       ...,

       [[155, 155, 155],
        [133, 133, 133],
        [131, 131, 131],
        ...,
        [ 51,  51,  51],
        [ 51,  51,  51],
        [ 50,  50,  50]],

       [[160, 160, 160],
        [111, 111, 111],
        [100, 100, 100],
        ...,
        [ 55,  55,  55],
        [ 54,  54,  54],
        [ 48,  48,  48]],

       [[155, 155, 155],
        [114, 114, 114],
        [ 98,  98,  98],
        ...,
        [ 58,  58,  58],
        [ 58,  58,  58],
        [ 50,  50,  50]]

In [17]:
df_train.head()

ImageId  ClassId                                      EncodedPixels
0  0002cc93b.jpg        1  29102 12 29346 24 29602 24 29858 24 30114 24 3...
1  0007a71bf.jpg        3  18661 28 18863 82 19091 110 19347 110 19603 11...
2  000a4bcdd.jpg        1  37607 3 37858 8 38108 14 38359 20 38610 25 388...
3  000f6bf48.jpg        4  131973 1 132228 4 132483 6 132738 8 132993 11 ...
4  0014fce06.jpg        3  229501 11 229741 33 229981 55 230221 77 230468...

In [18]:
images = []
classID = []
for image_id, class_id, encoded_bits in tqdm(df_train.values):
    img = cv2.imread(TRAIN_IMAGES + '/{}'.format(image_id), cv2.IMREAD_COLOR)
    img = img / 255
    images.append(img)
    classID.append(class_id)

100%|█████████████████████████████████████████████████████████████████████████████| 1000/1000 [00:09<00:00, 105.41it/s]


In [19]:
images[0]

array([[[0.2745098 , 0.2745098 , 0.2745098 ],
        [0.2745098 , 0.2745098 , 0.2745098 ],
        [0.26666667, 0.26666667, 0.26666667],
        ...,
        [0.18823529, 0.18823529, 0.18823529],
        [0.18823529, 0.18823529, 0.18823529],
        [0.19607843, 0.19607843, 0.19607843]],

       [[0.25882353, 0.25882353, 0.25882353],
        [0.26666667, 0.26666667, 0.26666667],
        [0.26666667, 0.26666667, 0.26666667],
        ...,
        [0.18823529, 0.18823529, 0.18823529],
        [0.19215686, 0.19215686, 0.19215686],
        [0.2       , 0.2       , 0.2       ]],

       [[0.23921569, 0.23921569, 0.23921569],
        [0.25098039, 0.25098039, 0.25098039],
        [0.25490196, 0.25490196, 0.25490196],
        ...,
        [0.19215686, 0.19215686, 0.19215686],
        [0.2       , 0.2       , 0.2       ],
        [0.21176471, 0.21176471, 0.21176471]],

       ...,

       [[0.60784314, 0.60784314, 0.60784314],
        [0.52156863, 0.52156863, 0.52156863],
        [0.51372549, 0

In [20]:
len(classID)

1000

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
df_train.head()

ImageId  ClassId                                      EncodedPixels
0  0002cc93b.jpg        1  29102 12 29346 24 29602 24 29858 24 30114 24 3...
1  0007a71bf.jpg        3  18661 28 18863 82 19091 110 19347 110 19603 11...
2  000a4bcdd.jpg        1  37607 3 37858 8 38108 14 38359 20 38610 25 388...
3  000f6bf48.jpg        4  131973 1 132228 4 132483 6 132738 8 132993 11 ...
4  0014fce06.jpg        3  229501 11 229741 33 229981 55 230221 77 230468...

In [23]:
df_train['Converted_pixels'] = images

In [46]:
X = images
y = df_train['ClassId'].values

In [47]:
len(images)

1000

In [48]:
from sklearn.preprocessing import LabelEncoder 

In [49]:
encoder = LabelEncoder()
y_converted = encoder.fit_transform(y)

In [50]:
from tensorflow.keras.utils import to_categorical

In [51]:
y_final = to_categorical(y_converted)

In [60]:
from sklearn.model_selection import train_test_split

In [79]:
y_final

array([[1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       ...,
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.]], dtype=float32)

In [67]:
y_final.shape

(1000, 4)

In [69]:
len(X_train)

700

In [72]:
len(X_cv)

300

In [73]:
X_cv

[array([[[0.37254902, 0.37254902, 0.37254902],
         [0.36470588, 0.36470588, 0.36470588],
         [0.35686275, 0.35686275, 0.35686275],
         ...,
         [0.35686275, 0.35686275, 0.35686275],
         [0.36078431, 0.36078431, 0.36078431],
         [0.34901961, 0.34901961, 0.34901961]],
 
        [[0.36078431, 0.36078431, 0.36078431],
         [0.36078431, 0.36078431, 0.36078431],
         [0.35686275, 0.35686275, 0.35686275],
         ...,
         [0.35686275, 0.35686275, 0.35686275],
         [0.35294118, 0.35294118, 0.35294118],
         [0.33333333, 0.33333333, 0.33333333]],
 
        [[0.37647059, 0.37647059, 0.37647059],
         [0.37647059, 0.37647059, 0.37647059],
         [0.37647059, 0.37647059, 0.37647059],
         ...,
         [0.37254902, 0.37254902, 0.37254902],
         [0.36470588, 0.36470588, 0.36470588],
         [0.34901961, 0.34901961, 0.34901961]],
 
        ...,
 
        [[0.40392157, 0.40392157, 0.40392157],
         [0.41960784, 0.41960784, 0.41960

In [74]:
X_train, X_cv, y_train, y_cv = train_test_split(X, y_final, random_state = 50, test_size = 0.3)

In [75]:
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.models import Sequential

In [76]:
model = Sequential()
model.add(Dense(100, activation = 'relu'))
model.add(Dense(50, activation = 'relu'))
model.add(Dense(10, activation = 'relu'))
model.add(Dense(4, activation = 'softmax'))

model.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [77]:
model.fit(X_train, y_train, epochs = 10, validation_data = (X_cv, y_cv))

AttributeError: 'list' object has no attribute 'shape'

In [ ]:
import cv2
import matplotlib.pyplot as plt

In [ ]:
img = plt.imread(train_path + '/{}'.format(images[0]))
plt.imshow(img)
plt.show()

In [ ]:
img.shape

In [ ]:
1600 * 3

In [ ]:
4800 / 69

In [ ]:
np.sqrt(4800)

In [ ]:
sample_submission = pd.read_csv('../input/severstal-steel-defect-detection/sample_submission.csv')

In [ ]:
sample_submission.head()

In [ ]:
df_train.head()

In [ ]:
np.array(df_train['EncodedPixels'].iloc[0])

In [ ]:
df_train.head()